from modules.bar.widgets.active_window import ActiveWindow
from modules.bar.widgets.volume import Volume
from modules.bar.widgets.language import Language
from modules.bar.widgets.workspaces import Workspaces
from modules.bar.widgets.date_time import DateTime
from modules.bar.widgets.media_player import MediaPlayer
from modules.bar.widgets.power import Power
from modules.bar.widgets.side_panel_button import SidePanelButton
from modules.bar.widgets.notifications import NotificationButton
from modules.bar.widgets.recording import Recording
from modules.bar.widgets.network import Network
from modules.bar.widgets.battery import Battery
from modules.bar.widgets.brightness import Brightness
from modules.bar.widgets.bluetooth import Bluetooth
from modules.bar.widgets.system_tray import SystemTray
